-- 20260501_questionnaire_copy_resync.sql
--
-- Resyncs the questionnaire copy in Supabase with the canonical strings
-- that previously lived as fallbacks in QuestionnaireSection.tsx, across
-- all four supported locales (en, pt_pt, ru, es).
--
-- The original seed (20260501_homepage_translations.sql) used
-- `on conflict do nothing`, so any rows already present with stale or
-- incorrect copy were never overwritten. This migration force-updates
-- every locale column for the 14 keys the component renders directly so
-- the UI shows the correct copy once the in-component fallbacks are gone.

insert into public.translations (namespace, key, en, pt_pt, ru, es) values
    ('questionnaire', 'intro.eyebrow',
        'Discover your match',
        'Descubra a sua escolha',
        'Найдите своё идеальное жильё',
        'Descubra su match'),
    ('questionnaire', 'intro.title',
        'Tell us what you seek',
        'Diga-nos o que procura',
        'Расскажите, что вы ищете',
        'Cuéntenos lo que busca'),
    ('questionnaire', 'intro.subtitle',
        'Answer a few quick questions to receive a list of exclusive listings curated for you.',
        'Responda a algumas perguntas rápidas para receber uma lista de imóveis exclusivos selecionados para si.',
        'Ответьте на несколько коротких вопросов и получите подборку эксклюзивных предложений, подобранных для вас.',
        'Responda a unas breves preguntas para recibir una lista de propiedades exclusivas seleccionadas para usted.'),
    ('questionnaire', 'progress.label',
        'Question {current} of {total}',
        'Pergunta {current} de {total}',
        'Вопрос {current} из {total}',
        'Pregunta {current} de {total}'),
    ('questionnaire', 'email.title',
        'Excited to see what Lume has for you?',
        'Curioso para ver o que a Lume tem para si?',
        'Хотите узнать, что Lume может вам предложить?',
        '¿Curioso por ver lo que Lume tiene para usted?'),
    ('questionnaire', 'email.subtitle',
        'Enter your email to receive our exclusive properties and services list.',
        'Introduza o seu e-mail para receber a nossa lista exclusiva de imóveis e serviços.',
        'Укажите свой e-mail, чтобы получить наш эксклюзивный список объектов и услуг.',
        'Introduzca su correo electrónico para recibir nuestra lista exclusiva de propiedades y servicios.'),
    ('questionnaire', 'email.placeholder',
        'your@email.com',
        'seu@email.com',
        'ваш@email.com',
        'su@email.com'),
    ('questionnaire', 'email.button',
        'Send',
        'Enviar',
        'Отправить',
        'Enviar'),
    ('questionnaire', 'email.button_loading',
        'Sending…',
        'A enviar…',
        'Отправка…',
        'Enviando…'),
    ('questionnaire', 'error.generic',
        'Something went wrong. Please try again.',
        'Ocorreu um erro. Por favor, tente novamente.',
        'Что-то пошло не так. Пожалуйста, попробуйте ещё раз.',
        'Algo salió mal. Por favor, inténtalo de nuevo.'),
    ('questionnaire', 'thanks.title',
        'Thank you!',
        'Obrigado!',
        'Спасибо!',
        '¡Gracias!'),
    ('questionnaire', 'thanks.message',
        'While we prepare your selection,',
        'Enquanto preparamos a sua seleção,',
        'Пока мы готовим вашу подборку,',
        'Mientras preparamos su selección,'),
    ('questionnaire', 'thanks.cta',
        'explore our current homes',
        'explore as nossas casas atuais',
        'познакомьтесь с нашими актуальными домами',
        'explore nuestras casas actuales'),
    ('questionnaire', 'thanks.close',
        'Close',
        'Fechar',
        'Закрыть',
        'Cerrar')
on conflict (namespace, key) do update set
    en    = excluded.en,
    pt_pt = excluded.pt_pt,
    ru    = excluded.ru,
    es    = excluded.es;
