-- 20260506_questionnaire_updates.sql
--
-- Questionnaire content changes:
--   * Relocation Q2: relabel options + add new "children" option.
--   * Relocation Q4: relabel + add new "1_year" option.
--   * Second Home: new regions question (q_regions, before lifestyle).
--   * Second Home Q4: relabel + add new "as_evolves" option.
--   * Exploring: new Q4 "What draws you to Portugal?" (q4_draws).
--   * Investment Q2: relabel all options (semantic shift) + add new
--     "guidance" option.
--   * Email screen title: "Let us prepare something for you".
--
-- All keys upserted across the four supported locales (en, pt_pt, ru, es).

insert into public.translations (namespace, key, en, pt_pt, ru, es) values

    -- ── Relocation Q2 ─────────────────────────────────────────────────────
    ('questionnaire', 'relocation.q2.title',
        'Who are you moving with?',
        'Com quem está a mudar-se?',
        'С кем вы переезжаете?',
        '¿Con quién se muda?'),
    ('questionnaire', 'relocation.q2.opt.solo',
        'Solo',
        'Sozinho',
        'Один',
        'Solo'),
    ('questionnaire', 'relocation.q2.opt.couple',
        'Couple',
        'Em casal',
        'Вдвоём',
        'En pareja'),
    ('questionnaire', 'relocation.q2.opt.children',
        'With children',
        'Com filhos',
        'С детьми',
        'Con hijos'),
    ('questionnaire', 'relocation.q2.opt.family',
        'Whole family',
        'Família inteira',
        'Всей семьёй',
        'Toda la familia'),

    -- ── Relocation Q4 ─────────────────────────────────────────────────────
    ('questionnaire', 'relocation.q4.title',
        'When are you planning to move?',
        'Quando planeia mudar-se?',
        'Когда вы планируете переезд?',
        '¿Cuándo planea mudarse?'),
    ('questionnaire', 'relocation.q4.opt.now',
        'Now',
        'Agora',
        'Сейчас',
        'Ahora'),
    ('questionnaire', 'relocation.q4.opt.6_months',
        '6 months',
        '6 meses',
        '6 месяцев',
        '6 meses'),
    ('questionnaire', 'relocation.q4.opt.1_year',
        '1 year',
        '1 ano',
        '1 год',
        '1 año'),
    ('questionnaire', 'relocation.q4.opt.exploring',
        'Exploring',
        'A explorar',
        'Изучаю варианты',
        'Explorando'),

    -- ── Second Home: new regions question ────────────────────────────────
    ('questionnaire', 'second_home.q_regions.title',
        'Which region speaks to you?',
        'Que região o atrai?',
        'Какой регион вам ближе?',
        '¿Qué región le atrae?'),
    ('questionnaire', 'second_home.q_regions.opt.lisboa',
        'Lisbon',
        'Lisboa',
        'Лиссабон',
        'Lisboa'),
    ('questionnaire', 'second_home.q_regions.opt.algarve',
        'Algarve',
        'Algarve',
        'Алгарве',
        'Algarve'),
    ('questionnaire', 'second_home.q_regions.opt.porto',
        'Porto',
        'Porto',
        'Порту',
        'Oporto'),
    ('questionnaire', 'second_home.q_regions.opt.alentejo',
        'Alentejo',
        'Alentejo',
        'Алентежу',
        'Alentejo'),

    -- ── Second Home Q4 ───────────────────────────────────────────────────
    ('questionnaire', 'second_home.q4.title',
        'How often will you visit?',
        'Com que frequência irá visitar?',
        'Как часто вы будете приезжать?',
        '¿Con qué frecuencia visitará?'),
    ('questionnaire', 'second_home.q4.opt.year_round',
        'Year-round',
        'Todo o ano',
        'Круглый год',
        'Todo el año'),
    ('questionnaire', 'second_home.q4.opt.seasonally',
        'Seasonally',
        'Por temporadas',
        'По сезонам',
        'Por temporadas'),
    ('questionnaire', 'second_home.q4.opt.holidays_only',
        'Holidays only',
        'Apenas em férias',
        'Только в отпуск',
        'Solo en vacaciones'),
    ('questionnaire', 'second_home.q4.opt.as_evolves',
        'As it evolves / When possible',
        'Conforme evolui / Quando possível',
        'По обстоятельствам / Когда получится',
        'Según evolucione / Cuando sea posible'),

    -- ── Exploring: new Q4 ────────────────────────────────────────────────
    ('questionnaire', 'exploring.q4.title',
        'What draws you to Portugal?',
        'O que o atrai a Portugal?',
        'Что вас привлекает в Португалии?',
        '¿Qué le atrae de Portugal?'),
    ('questionnaire', 'exploring.q4.opt.slower_pace',
        'A slower pace of life',
        'Um ritmo de vida mais calmo',
        'Более размеренный ритм жизни',
        'Un ritmo de vida más pausado'),
    ('questionnaire', 'exploring.q4.opt.culture',
        'Culture & architecture',
        'Cultura e arquitetura',
        'Культура и архитектура',
        'Cultura y arquitectura'),
    ('questionnaire', 'exploring.q4.opt.nature',
        'Nature & landscape',
        'Natureza e paisagem',
        'Природа и пейзажи',
        'Naturaleza y paisaje'),
    ('questionnaire', 'exploring.q4.opt.possibility',
        'A sense of possibility',
        'Um sentido de possibilidade',
        'Ощущение новых возможностей',
        'Un sentido de posibilidad'),

    -- ── Investment Q2 (relabel + new "guidance") ─────────────────────────
    ('questionnaire', 'investment.q2.opt.lead',
        'Leading a project',
        'Liderar um projeto',
        'Возглавить проект',
        'Liderar un proyecto'),
    ('questionnaire', 'investment.q2.opt.co',
        'Joining selectively',
        'Participar de forma seletiva',
        'Участвовать выборочно',
        'Participar de forma selectiva'),
    ('questionnaire', 'investment.q2.opt.guidance',
        'Relying on guidance',
        'Confiar em aconselhamento',
        'Полагаться на сопровождение',
        'Confiar en el asesoramiento'),
    ('questionnaire', 'investment.q2.opt.various',
        'Taking time to understand',
        'Levar tempo para compreender',
        'Не спешить и разобраться',
        'Tomarse tiempo para entender'),

    -- ── Email screen title ───────────────────────────────────────────────
    ('questionnaire', 'email.title',
        'Let us prepare something for you',
        'Deixe-nos preparar algo para si',
        'Позвольте нам подготовить кое-что для вас',
        'Permítanos preparar algo para usted')

on conflict (namespace, key) do update set
    en    = excluded.en,
    pt_pt = excluded.pt_pt,
    ru    = excluded.ru,
    es    = excluded.es;
